spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prompter-db.cnlylxr7zuzj.ap-northeast-2.rds.amazonaws.com:3306/prompterdb?useSSL=false & allowPublicKeyRetrieval=true
    username: admin
    password: prompterrds
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    defer-datasource-initialization: true
    #    hibernate:
    #      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        globally_quoted_identifiers: true   # SQL 문이 실행될 때 틸드(`)로 테이블과 컬럼을 자동으로 감싸주는 설정
        generate_statistics: true   # 쿼리 수행 통계를 확인
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  redis:
    host: localhost
    port: 6379

client:
  openAiApi:
    baseUrl: http://64.110.80.114:5000
  google:
    baaseUrl: https://translation.googleapis.com/v3/projects